# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-19 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='describe',
            field=models.CharField(default='', max_length=255, verbose_name='描述'),
        ),
    ]
