# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-19 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_permission_describe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('views_student_list', '查看学员信息表'), ('views_student_info', '查看学员详细信息'), ('home', '登录首页')), 'verbose_name': '权限表', 'verbose_name_plural': '权限表'},
        ),
    ]
